name: flutter_braintree_corevasion
description: Flutter plugin that wraps the native Braintree SDKs. Enables payments with credit cards, PayPal, Google Pay and more.
version: 2.0.7
homepage: https://github.com/profkaygee/flutter-braintree

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_braintree_corevasion
        pluginClass: FlutterBraintreePlugin
      ios:
        pluginClass: FlutterBraintreePlugin
